apiVersion: v1
kind: Pod
metadata:
  name: requests-pod-test
spec:
  containers:
    - name: main
      image: busybox
      command: ["dd", "if=/dev/zero", "of=/dev/null"]
      resources:
        requests:
          cpu: 3000m # The container requests 200 millicores (that is, 1/5 of a single CPU core’s time).
          memory: 20Mi # The container also requests 10 mebibytes of memory.
