apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - image: golang-docker-example
          imagePullPolicy: IfNotPresent
          name: kubia
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 10m

---
apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  selector:
    app: kubia
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
