apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: demo-server
          imagePullPolicy: IfNotPresent
          name: demo
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  selector:
    app: demo
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
