apiVersion: apps/v1 # change version API
kind: Deployment # change resource name
metadata:
  name: demo # The name of the pod
spec:
  replicas: 10 # number of the pod init
  strategy: # deploy strategy
    type: RollingUpdate # strategy type is Recreate or RollingUpdate.
  selector: # The pod selector determining what pods the RC is operating on
    matchLabels: # change (replace ReplicationController as ReplicaSets)
      app: demo # label value
  template: # pod template
    metadata:
      labels:
        app: demo # label value
    spec:
      containers:
        - image: vinhtc27/demo-server:latest # Image to run the container
          imagePullPolicy: Always
          name: demo # The name of the container
          ports:
            - containerPort: 3000 # Pod of the container
          resources:
            requests:
              cpu: 100m #The container requests 10 millicores
              memory: 50Mi
      terminationGracePeriodSeconds: 10

---
apiVersion: v1 # Descriptor conforms to version v1 of Kubernetes API
kind: Service # Select Pod resource
metadata:
  name: demo
spec:
  selector:
    app: demo # label selectors Pod
  #type: NodePort # type NodePort
  type: LoadBalancer # type LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80 # port of the serivce
      targetPort: 3000 # port of the container that service will forward to
